### ISSUE TITLE
Faulty (?) imports in tests

### ISSUE THREAD

**Issue by sirmarcel** [fabiannagel/schnax#10]
Many tests currently contain lines like:

```python
import tests.test_utils.initialize as init
```

which cause my test runner (`nosetests`) to fail with errors like:

```
ModuleNotFoundError: No module named 'tests'
```

My intention was for tests to be run by executing the test runner from *within* the `tests/` directory. This is why the `assets` are addressed by relative paths, and why originally, imports directly from `test_utils` were used. Can we revert to this approach?

**Comment by fabiannagel** [comment]
Fixed - testing now works from root directory using `nose2`.
